name: Build Custom RustDesk Client

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server z.B. mra.dyndd.de'
        required: true
      port:
        description: 'Port z.B. 21116'
        required: true
        default: '21116'
      key:
        description: 'Public Key aus id_ed25519.pub'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download RustDesk 1.2.3 Sciter
        run: |
          curl -L -o rustdesk.exe https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86-sciter.exe

      - name: Download 7z SFX Module
        run: |
          curl -L -o 7z-extra.7z https://www.7-zip.org/a/7z2301-extra.7z
          7z x 7z-extra.7z 7zS.sfx -o.

      - name: Check files
        shell: cmd
        run: dir

      - name: Create Config
        shell: cmd
        run: |
          echo [options] > RustDesk2.toml
          echo custom-rendezvous-server = "${{ github.event.inputs.server }}:${{ github.event.inputs.port }}" >> RustDesk2.toml
          echo key = "${{ github.event.inputs.key }}" >> RustDesk2.toml
          echo relay-server = "${{ github.event.inputs.server }}" >> RustDesk2.toml

      - name: Create SFX Config
        shell: cmd
        run: |
          echo ;!@Install@!UTF-8! > config.txt
          echo Title="Support" >> config.txt
          echo GUIMode="2" >> config.txt
          echo RunProgram="cmd /c if not exist \"%%APPDATA%%\\RustDesk\\config\" mkdir \"%%APPDATA%%\\RustDesk\\config\" ^& copy /Y RustDesk2.toml \"%%APPDATA%%\\RustDesk\\config\\\" ^& start \"\" rustdesk.exe" >> config.txt
          echo ;!@InstallEnd@! >> config.txt

      - name: Build Support.exe
        shell: cmd
        run: |
          7z a temp.7z rustdesk.exe RustDesk2.toml
          copy /b 7zS.sfx+config.txt+temp.7z Support.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Support.exe
          path: Support.exe
