name: Build Custom RustDesk Client
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server z.B. mein.server.de:21116'
        required: true
      key:
        description: 'Public Key aus id_ed25519.pub'
        required: true
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Build RustDesk
        run: cargo build --release --features inline
        env:
          RENDEZVOUS_SERVER: ${{ github.event.inputs.server }}
          RS_PUB_KEY: ${{ github.event.inputs.key }}
          
      - name: Rename
        run: Rename-Item target/release/rustdesk.exe Support.exe
        if: success()
        
      - uses: actions/upload-artifact@v4
        with:
          name: Support.exe
          path: Support.exe
        if: success()
