name: Build Custom RustDesk Client
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server'
        required: true
        default: 'dein-server.de:21116'
      key:
        description: 'Public Key'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Build RustDesk
        run: cargo build --release --features inline
        env:
          RENDEZVOUS_SERVER: ${{ github.event.inputs.server }}
          RS_PUB_KEY: ${{ github.event.inputs.key }}
      - name: Rename and Upload
        run: Rename-Item target/release/rustdesk.exe Support.exe
      - uses: actions/upload-artifact@v3
        with:
          name: Support.exe
          path: Support.exe
